#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1528397347.457929
__CHEETAH_genTimestamp__ = 'Thu Jun  7 11:49:07 2018'
__CHEETAH_src__ = 'channel.tmpl'
__CHEETAH_srcLastModified__ = 'Thu Jun  7 11:47:14 2018'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class channel(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(channel, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''# Created on ''')
        _v = VFFSL(SL,"date",True) # u'${date}' on line 1, col 14
        if _v is not None: write(_filter(_v, rawExpr=u'${date}')) # from line 1, col 14.
        write(u'''
# Author: ''')
        _v = VFFSL(SL,"user",True) # u'${user}' on line 2, col 11
        if _v is not None: write(_filter(_v, rawExpr=u'${user}')) # from line 2, col 11.
        write(u'''
''')
        write(u'''# THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT!!!
''')
        write(u'''# XML Source: ''')
        _v = VFFSL(SL,"source",True) # u'${source}' on line 6, col 15
        if _v is not None: write(_filter(_v, rawExpr=u'${source}')) # from line 6, col 15.
        write(u'''

# COMPONENT: "''')
        _v = VFFSL(SL,"component_string",True) # u'${component_string}' on line 8, col 15
        if _v is not None: write(_filter(_v, rawExpr=u'${component_string}')) # from line 8, col 15.
        write(u'''"
TELEMETRY ''')
        _v = VFFSL(SL,"target_caps",True) # u'${target_caps}' on line 9, col 11
        if _v is not None: write(_filter(_v, rawExpr=u'${target_caps}')) # from line 9, col 11.
        write(u''' ''')
        _v = VFFSL(SL,"channel_name",True) # u'${channel_name}' on line 9, col 26
        if _v is not None: write(_filter(_v, rawExpr=u'${channel_name}')) # from line 9, col 26.
        write(u''' ''')
        _v = VFFSL(SL,"endianness",True) # u'${endianness}' on line 9, col 42
        if _v is not None: write(_filter(_v, rawExpr=u'${endianness}')) # from line 9, col 42.
        write(u''' "''')
        _v = VFFSL(SL,"chn_desc",True) # u'${chn_desc}' on line 9, col 57
        if _v is not None: write(_filter(_v, rawExpr=u'${chn_desc}')) # from line 9, col 57.
        write(u'''"
    ''')
        write(_filter( render "_${target_lower}_tlm_chn_hdr.txt", locals: {id: ${id}}))
        write(u'''
    APPEND_ITEM VALUE ''')
        _v = VFFSL(SL,"value_bits",True) # u'${value_bits}' on line 11, col 23
        if _v is not None: write(_filter(_v, rawExpr=u'${value_bits}')) # from line 11, col 23.
        write(u''' ''')
        _v = VFFSL(SL,"value_type",True) # u'${value_type}' on line 11, col 37
        if _v is not None: write(_filter(_v, rawExpr=u'${value_type}')) # from line 11, col 37.
        write(u''' ''')
        _v = VFFSL(SL,"value_desc",True) # u'${value_desc}' on line 11, col 51
        if _v is not None: write(_filter(_v, rawExpr=u'${value_desc}')) # from line 11, col 51.
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_channel= 'respond'

## END CLASS DEFINITION

if not hasattr(channel, '_initCheetahAttributes'):
    templateAPIClass = getattr(channel, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(channel)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=channel()).run()


